apiVersion: batch/v1
kind: Job
metadata:
  name: biocontainers-pipelines-onetime-run
spec:
  template:
    spec:
      containers:
        - name: biocontainers-pipelines
          image: chakrabandla/biocontainer-pipelines:e66fb8aaf361a62befc52ba47d75701b91689cf9
          imagePullPolicy: IfNotPresent
          env:
            - name: "MONGO_ROOT_PASS"
              value: {{ .Values.mongodb.mongodbRootPassword}}
            - name: "BIOCONT_DB_NAME"
              value: {{ .Values.biocont_db_name }}
            - name: "MONGODB_ADMIN_DB"
              value: {{ .Values.mongodb.mongodbDatabase }}
            - name: "MONGODB_PASS"
              value: {{ .Values.mongodb.mongodbPassword }}
            - name: "MONGODB_USER"
              value: {{ .Values.mongodb.mongodbUsername }}
            - name: "MONGODB_HOST"
              value: {{ template "mongodb.fullname" . }}
            - name: "MONGODB_PORT"
              value: {{ .Values.mongodb.port }}
            - name: PIPELINE_ARGS
              value: "-k -q -s -ad -aq -ac -aw -ai -am -af"
            - name: SLACK_CHANNEL
              value: {{ .Values.slack.bioctainerPrideSlackChannel }}
            - name: SLACK_REPORT_URL
              value: {{ .Values.slack.bioctainerPrideWebhookUrl }}
          args:
            - /bin/sh
            - /biocontainers-backend/run.sh
      restartPolicy: OnFailure