# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from biocontainers_flask_server.models.base_model_ import Model
from biocontainers_flask_server import util


class DescriptorType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    CWL = "CWL"
    WDL = "WDL"
    NFL = "NFL"

    def __init__(self):  # noqa: E501
        """DescriptorType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DescriptorType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DescriptorType of this DescriptorType.  # noqa: E501
        :rtype: DescriptorType
        """
        return util.deserialize_model(dikt, cls)
