# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from biocontainers_flask.server.models.base_model_ import Model
from biocontainers_flask.server import util


class ImageType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DOCKER = "Docker"
    SINGULARITY = "Singularity"
    CONDA = "Conda"
    def __init__(self):  # noqa: E501
        """ImageType - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ImageType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageType of this ImageType.  # noqa: E501
        :rtype: ImageType
        """
        return util.deserialize_model(dikt, cls)
