# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from biocontainers_flask.server.models.base_model_ import Model
from biocontainers_flask.server import util


class ServiceOrganization(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, url: str=None):  # noqa: E501
        """ServiceOrganization - a model defined in Swagger

        :param name: The name of this ServiceOrganization.  # noqa: E501
        :type name: str
        :param url: The url of this ServiceOrganization.  # noqa: E501
        :type url: str
        """
        self.swagger_types = {
            'name': str,
            'url': str
        }

        self.attribute_map = {
            'name': 'name',
            'url': 'url'
        }
        self._name = name
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceOrganization':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Service_organization of this ServiceOrganization.  # noqa: E501
        :rtype: ServiceOrganization
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ServiceOrganization.

        Name of the organization responsible for the service  # noqa: E501

        :return: The name of this ServiceOrganization.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ServiceOrganization.

        Name of the organization responsible for the service  # noqa: E501

        :param name: The name of this ServiceOrganization.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def url(self) -> str:
        """Gets the url of this ServiceOrganization.

        URL of the website of the organization (RFC 3986 format)  # noqa: E501

        :return: The url of this ServiceOrganization.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """Sets the url of this ServiceOrganization.

        URL of the website of the organization (RFC 3986 format)  # noqa: E501

        :param url: The url of this ServiceOrganization.
        :type url: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url
