# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from biocontainers_flask.server.models.base_model_ import Model
from biocontainers_flask.server import util


class ToolClass(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, description: str=None):  # noqa: E501
        """ToolClass - a model defined in Swagger

        :param id: The id of this ToolClass.  # noqa: E501
        :type id: str
        :param name: The name of this ToolClass.  # noqa: E501
        :type name: str
        :param description: The description of this ToolClass.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'description': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description'
        }

        self._id = id
        self._name = name
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'ToolClass':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ToolClass of this ToolClass.  # noqa: E501
        :rtype: ToolClass
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ToolClass.

        The unique identifier for the class  # noqa: E501

        :return: The id of this ToolClass.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ToolClass.

        The unique identifier for the class  # noqa: E501

        :param id: The id of this ToolClass.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ToolClass.

        A short friendly name for the class  # noqa: E501

        :return: The name of this ToolClass.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ToolClass.

        A short friendly name for the class  # noqa: E501

        :param name: The name of this ToolClass.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ToolClass.

        A longer explanation of what this class is and what it can accomplish  # noqa: E501

        :return: The description of this ToolClass.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ToolClass.

        A longer explanation of what this class is and what it can accomplish  # noqa: E501

        :param description: The description of this ToolClass.
        :type description: str
        """

        self._description = description
