name: Biocontainer pipelines publish Docker image
env:
  IMAGE_NAME: biocontainer-pipelines

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: echo envs
        run: |
          echo $IMAGE_TAG
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
      - name: Build the Docker image
        run: |
          cd dockerfiles/pipelines/
          pwd
          docker build --build-arg CACHEBUST=$(date +%s) --tag $IMAGE_NAME:$GITHUB_SHA .
#          docker tag $IMAGE_NAME:$GITHUB_SHA ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:$GITHUB_SHA
#      - name: push docker image to dockerhub
#        run: |
#          docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PWD }}
#          docker push ${{ secrets.DOCKERHUB_USER }}/$IMAGE_NAME:$GITHUB_SHA